CRUD.UI/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts.Interfaces;

namespace CRUDUI.Controllers
{
    //[Authorize(Roles = "Admin")]
    [Route("[controller]/[action]")] //Route Tokens
    public class CountriesController : Controller
    {
        private readonly ICountriesService _countriesService;

        public CountriesController(ICountriesService countriesService)
        {
            _countriesService = countriesService;
        }

        public IActionResult UploadFromExcel()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadFromExcel(IFormFile excelFile)
        {
            if (excelFile == null || excelFile.Length == 0)
            {
                ViewBag.ErrorMessage = "Please select an xlsx file";
                return View();
            }

            if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
            {
                ViewBag.ErrorMessage = "Unsupported file. 'xlsx' file is expected";
                return View();
            }

            int countriesCountInserted = await _countriesService.UploadCountriesFromExcelFile(excelFile);

            ViewBag.Message = $"{countriesCountInserted} Countries Uploaded";
            return View();
        }
    }
}

CRUD.UI/Views/Countries/UploadFromExcel.cshtml
@{
    ViewBag.Title = "Upload Countries from Excel";
}
<div class="container">
    <form asp-controller="Countries" asp-action="UploadFromExcel" method="post" enctype="multipart/form-data">
        <div class="form-group">
            <label for="excelFile">Select xlsx file to upload:</label>
            <input type="file" class="form-control-file p-2" id="excelFile" name="excelFile">
            <button type="submit" class="btn btn-primary">Upload</button>
        </div>
        <div class="text-danger">@ViewBag.ErrorMessage</div>
        <div class="text-success">@ViewBag.Message</div>
    </form>
</div>